import type { AtlasEntry, AtlasFamily, AtlasKind, AtlasSide } from "./types";

function e(
  id: string,
  name: string,
  eco: string,
  family: AtlasFamily,
  kind: AtlasKind,
  sides: AtlasSide | AtlasSide[],
  moves: string,
  routes: [name: string, san: string, note: string][],
  attacking: string,
  positional: string,
  trainId?: string,
): AtlasEntry {
  return {
    id,
    name,
    eco,
    family,
    kind,
    sides: Array.isArray(sides) ? sides : [sides],
    moves,
    routes: routes.map(([routeName, san, note]) => ({
      name: routeName,
      san,
      note,
    })),
    attacking,
    positional,
    trainId,
  };
}

/** Mainstream atlas — club-level routes and plans. Validated at build. */
export const ATLAS: AtlasEntry[] = [
  e(
    "italian-game",
    "Italian Game",
    "C50",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 Bc4",
    [
      ["Giuoco", "Bc5 c3 Nf6 d4", "c3 then d4. Open the middle."],
      ["Two Knights", "Nf6 d3 Be7", "Quiet d3. Castle, then c3-d4 later."],
    ],
    "Aim at f7 with the bishop. Castle fast, then push d4.",
    "Don't rush Ng5 unless they leave f7 loose. Develop, then break.",
    "italian-attack",
  ),
  e(
    "giuoco-piano",
    "Giuoco Piano",
    "C50",
    "open",
    "semi",
    ["white", "black"],
    "e4 e5 Nf3 Nc6 Bc4 Bc5",
    [
      ["Piano", "c3 Nf6 d3", "Slow Italian. d3, knights, then d4."],
      ["Center", "c3 Nf6 d4 exd4 cxd4", "Open the middle while they are uncastled."],
    ],
    "Hit the center with d4. Keep the Italian bishop staring at f7.",
    "Trade only when it helps your center. Castle, then c3-d4.",
  ),
  e(
    "two-knights",
    "Two Knights Defense",
    "C55",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nc6 Bc4 Nf6",
    [
      ["Quiet", "d3 Bc5 O-O", "Both castle. Then c3 and a later d4."],
      ["Knight raid", "Ng5 d5 exd5", "They eye f7. You open the center."],
    ],
    "If they go Ng5, strike d5 and don't panic about f7.",
    "Develop the bishop, castle, and hold e5 as a rock.",
  ),
  e(
    "fried-liver",
    "Fried Liver",
    "C57",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5",
    [
      ["Liver", "Nxf7 Kxf7 Qf3+", "Check the king. Hunt with queen and bishop."],
      ["Lolli", "d4", "Open the center first. The king still sits on e8."],
    ],
    "Sacrifice on f7 only if the queen check comes next.",
    "If they decline the knight, just take on d5 and stay developed.",
    "italian-attack",
  ),
  e(
    "traxler",
    "Traxler Counterattack",
    "C57",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Bc5",
    [
      ["Take f7", "Nxf7 Bxf2+", "You check first. Their king walks too."],
      ["Bishop take", "Bxf7+ Ke7", "King steps up. Then d5 and pieces fly."],
    ],
    "Give a check on f2 and hunt their king before yours falls.",
    "Only play this if you know the first five checks. Else castle.",
    "italian-attack",
  ),
  e(
    "evans-gambit",
    "Evans Gambit",
    "C51",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 Bc4 Bc5 b4",
    [
      ["Accepted", "Bxb4 c3 Ba5 d4", "c3 and d4. Tempo for the center."],
      ["Declined", "Bb6 a4 a6 Nc3", "Space on the queenside. Still castle."],
    ],
    "Give the b-pawn. Take the center and point every piece at f7.",
    "Don't hunt pawns back. Castle, open d, and keep the bishop pair.",
    "evans-gambit",
  ),
  e(
    "hungarian",
    "Hungarian Defense",
    "C50",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nc6 Bc4 Be7",
    [
      ["Solid", "d4 d6", "Small center. Castle and wait."],
      ["Kick", "c3 Nf6 d3", "They build c3-d4. You stay compact."],
    ],
    "Don't get fancy. Castle, then …d6 and …Be6 to blunt their bishop.",
    "Hold e5. Trade their Italian bishop when you can do it safely.",
  ),
  e(
    "scotch-game",
    "Scotch Game",
    "C45",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 d4",
    [
      ["Main", "exd4 Nxd4 Nf6 Nc3", "Open d-file. Knights in the middle."],
      ["Mieses", "exd4 Nxd4 Nf6 Nxc6 bxc6 e5", "Push e5. Cramp their knight."],
    ],
    "Open d4 on move three. Recapture and use the open files.",
    "Castle, then decide if e5 or Be3 is the squeeze.",
  ),
  e(
    "scotch-gambit",
    "Scotch Gambit",
    "C44",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 d4 exd4 Bc4",
    [
      ["Wedge", "Nf6 e5 d5 Bb5", "e5 wedge. Pin the knight on c6."],
      ["Safe take", "Bc5 c3 Nf6", "They develop. You still want c3-d4."],
    ],
    "Leave the d-pawn. Develop Bc4 and sit a pawn on e5.",
    "Ruin their c-pawns, castle, then f4 and the e-file.",
    "scotch-gambit",
  ),
  e(
    "four-knights-scotch",
    "Scotch Four Knights",
    "C47",
    "open",
    "semi",
    ["white", "black"],
    "e4 e5 Nf3 Nc6 Nc3 Nf6 d4",
    [
      ["Trade", "exd4 Nxd4 Bb4 Nxc6", "Bishops come out. Keep it simple."],
      ["Belgrade", "exd4 Nd5", "Knight hop. Tactics in the center."],
    ],
    "Open the middle while all four knights are out.",
    "Castle, trade one pair of knights, and play on the open d-file.",
  ),
  e(
    "ruy-lopez",
    "Ruy Lopez",
    "C60",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 Bb5",
    [
      ["Closed", "a6 Ba4 Nf6 O-O Be7", "Castle, then c3 and d4."],
      ["Berlin", "Nf6 O-O Nxe4 d4", "They grab e4. You take the center."],
    ],
    "Pressure e5. When ready, c3 and d4 blow the middle open.",
    "Keep the Spanish bishop until it has a job. Don't trade for air.",
  ),
  e(
    "ruy-berlin",
    "Berlin Defense",
    "C65",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nc6 Bb5 Nf6",
    [
      ["Endgame", "O-O Nxe4 d4 Nd6", "Queens may come off. King walks to c8."],
      ["Closed", "O-O Be7 Re1", "Keep queens. Castle and hold e5."],
    ],
    "If queens stay, hit back with …d5 when the e-file opens.",
    "In the Berlin ending, don't rush …c5. Piece activity first.",
  ),
  e(
    "ruy-marshall",
    "Marshall Attack",
    "C89",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5",
    [
      ["Accepted", "exd5 Nxd5 Nxe5 Nxe5 Rxe5", "You gave a pawn. Attack the king."],
      ["Anti", "h3", "They dodge. You still have a free …d5 idea later."],
    ],
    "Give the e-pawn. Swing the queen to h4 and point bishops at g2.",
    "Only play it if you remember the first attacking loop. Else …d6.",
  ),
  e(
    "ruy-exchange",
    "Ruy Lopez Exchange",
    "C68",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6",
    [
      ["Take", "dxc6 O-O", "You doubled their pawns. Castle and play d4."],
      ["Early d4", "dxc6 d4", "Open at once. Trade into a good ending."],
    ],
    "Take on c6, then d4. Their bishop pair is the only worry.",
    "In endings, your 4 vs 3 kingside pawns want to roll.",
  ),
  e(
    "petrov",
    "Petrov Defense",
    "C42",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 Nf6",
    [
      ["Classical", "Nxe5 d6 Nf3 Nxe4", "Copy, then break the copy with …d5."],
      ["Steinitz", "d4 Nxe4 Bd3", "They take the center. You stay solid."],
    ],
    "Don't copy forever. After …Nxe4, play …d5 and develop.",
    "Trade one pair of knights and castle. The position is a slow squeeze.",
  ),
  e(
    "four-knights",
    "Four Knights Game",
    "C47",
    "open",
    "semi",
    ["white", "black"],
    "e4 e5 Nf3 Nc6 Nc3 Nf6",
    [
      ["Spanish", "Bb5 Bb4", "Pins both sides. Castle and d3/d4."],
      ["Scotch", "d4 exd4 Nxd4", "Open it. Same as Scotch Four Knights."],
    ],
    "Pin a knight or open d4. Don't shuffle forever.",
    "Castle, break with d4 (or …d5), and use the open file.",
  ),
  e(
    "ponziani",
    "Ponziani Opening",
    "C44",
    "open",
    "semi",
    "white",
    "e4 e5 Nf3 Nc6 c3",
    [
      ["Center", "Nf6 d4", "c3 supports d4. Classic open-game plan."],
      ["Jaenisch", "d5 Qa4", "They strike …d5. Pin and keep the pawn."],
    ],
    "Play d4 on the next breath. The c-pawn is there for that.",
    "If they hit …d5, don't panic. Develop and castle.",
  ),
  e(
    "philidor",
    "Philidor Defense",
    "C41",
    "open",
    "system",
    "black",
    "e4 e5 Nf3 d6",
    [
      ["Hanham", "d4 Nd7", "Hold e5. Knights to d7 and f6, then castle."],
      ["Exchange", "d4 exd4 Nxd4 Nf6", "Open the middle. Stay compact."],
    ],
    "Don't get squeezed. After …Nd7 and …Be7, look for …f5 later.",
    "Keep the e5 point. The Lion setup is the grown-up version.",
    "black-lion",
  ),
  e(
    "latvian",
    "Latvian Gambit",
    "C40",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 f5",
    [
      ["Take", "Nxe5 Qf6", "You lost a pawn. Hunt e5 and f2."],
      ["Center", "d4 fxe4 Nxe5", "They open d. You still want checks."],
    ],
    "Only if you like chaos. Check on the f-file and don't castle late.",
    "If they decline, develop and treat it like a wild King's Gambit.",
  ),
  e(
    "elephant",
    "Elephant Gambit",
    "C40",
    "open",
    "semi",
    "black",
    "e4 e5 Nf3 d5",
    [
      ["Take e", "exd5 e4", "Push the e-pawn. Kick their knight."],
      ["Take d", "Nxe5 Bd6", "Develop with tempo. Castle short."],
    ],
    "Open the center at once and use the e-file.",
    "If the gambit fails, just develop and don't throw a second pawn.",
  ),
  e(
    "kings-gambit",
    "King's Gambit",
    "C30",
    "open",
    "semi",
    "white",
    "e4 e5 f4",
    [
      ["Accepted", "exf4 Nf3 g5", "Stop …Qh4. Then d4 and Bc4."],
      ["Declined", "Bc5 Nf3 d6", "They hold e5. You still castle long or short."],
    ],
    "Open the f-file and point the bishop at f7.",
    "Knight to f3 first — never let …Qh4+ wreck the king.",
    "kings-gambit",
  ),
  e(
    "kga",
    "King's Gambit Accepted",
    "C33",
    "open",
    "semi",
    ["white", "black"],
    "e4 e5 f4 exf4",
    [
      ["Knight", "Nf3 g5 h4", "Rip the kingside pawns. Then Bc4."],
      ["Bishop", "Bc4 Qh4+ Kf1", "King walks. You still want d4 and Nf3."],
    ],
    "Get the f-file and a bishop on c4. Their king is the prize.",
    "Don't grab every pawn. Castle (even by walking) and use the file.",
    "kings-gambit",
  ),
  e(
    "kgd",
    "King's Gambit Declined",
    "C30",
    "open",
    "semi",
    "black",
    "e4 e5 f4 Bc5",
    [
      ["Classical", "Nf3 d6", "Hold e5. Castle and hit f4 later."],
      ["Center", "Nf3 d6 c3", "They build d4. You stay on the a7–g1 diagonal."],
    ],
    "Keep the bishop on c5 so they cannot castle in comfort.",
    "Take on f4 only when you can hold the extra pawn.",
  ),
  e(
    "vienna",
    "Vienna Game",
    "C25",
    "open",
    "semi",
    "white",
    "e4 e5 Nc3",
    [
      ["Quiet", "Nf6 Bc4", "Italian-style. Then f4 or d3."],
      ["Gambit", "Nf6 f4", "Vienna Gambit. Open f and hit e5."],
    ],
    "If they allow f4, take the file. Else Bc4 and castle.",
    "Don't play Nf3 too early if you still want the f-pawn break.",
  ),
  e(
    "vienna-gambit",
    "Vienna Gambit",
    "C29",
    "open",
    "semi",
    "white",
    "e4 e5 Nc3 Nf6 f4",
    [
      ["Accepted", "d5 fxe5 Nxe4", "Center opens. Develop and castle."],
      ["Declined", "d6 Nf3", "They hold. You still castle and play d4."],
    ],
    "Break f4, then use the e-file and the c4 bishop.",
    "If …d5 comes, take, develop, and don't hang e4.",
    "vienna-gambit",
  ),
  e(
    "bishops-opening",
    "Bishop's Opening",
    "C23",
    "open",
    "semi",
    "white",
    "e4 e5 Bc4",
    [
      ["Italian path", "Nf6 d3", "Can transpose to a slow Italian."],
      ["Vienna path", "Nc6 Nc3", "Knights out, then f4 or d3."],
    ],
    "Eye f7 from move two. Castle and break d4.",
    "Don't play f4 until the king is safe and Nf3 is ready.",
  ),
  e(
    "center-game",
    "Center Game",
    "C22",
    "open",
    "semi",
    "white",
    "e4 e5 d4 exd4 Qxd4",
    [
      ["Main", "Nc6 Qe3 Nf6", "Queen steps aside. Then Bd2 and O-O-O."],
      ["Early castle", "Nc6 Qe3 Nf6 Nc3", "Develop, castle long, storm the kingside."],
    ],
    "Castle long and throw the kingside pawns.",
    "Don't let the queen get chased forever. Park it on e3.",
  ),
  e(
    "danish",
    "Danish Gambit",
    "C21",
    "open",
    "semi",
    "white",
    "e4 e5 d4 exd4 c3",
    [
      ["Accepted", "dxc3 Bc4 cxb2 Bxb2", "Two bishops. Hunt f7 and the king."],
      ["Declined", "d5 exd5 Nf6", "They give the pawn back. Play a normal open game."],
    ],
    "Give two pawns for both bishops and a direct attack.",
    "If they decline, take the center and castle like a grown-up.",
  ),
  e(
    "sicilian",
    "Sicilian Defense",
    "B20",
    "semi-open",
    "semi",
    "black",
    "e4 c5",
    [
      ["Open", "Nf3 d6 d4", "They take the center. You get the c-file."],
      ["Alapin", "c3 Nf6", "They want d4. Hit e4 and stay flexible."],
    ],
    "Trade a wing pawn for a center pawn, then use the c-file.",
    "Don't castle into a ready Yugoslav storm. Count their pieces first.",
  ),
  e(
    "najdorf",
    "Sicilian Najdorf",
    "B90",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
    [
      ["English Attack", "Be3 e5 Nb3 Be6", "…e5 grabs space. Then …Be7 and …O-O."],
      ["Classical", "Be2 e5 Nb3 Be7", "Quieter. Castle and play …b5."],
    ],
    "Play …e5 or …e6, then …b5 and a knight hop to c4 or b6.",
    "The a6 pawn stops Nb5. Don't forget …Be7 before you get wild.",
  ),
  e(
    "dragon",
    "Sicilian Dragon",
    "B70",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
    [
      ["Yugoslav", "Be3 Bg7 f3 O-O Qd2", "They castle long. You exchange on c3."],
      ["Classical", "Be2 Bg7 O-O O-O", "Both short. Play …Nc6 and …d5."],
    ],
    "Fianchetto, then …Rc8 and a sacrifice on c3.",
    "Don't castle if their h-pawn is already running. Time the exchange.",
    "dragon",
  ),
  e(
    "accel-dragon",
    "Accelerated Dragon",
    "B32",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6",
    [
      ["Maroczy", "c4 Bg7", "They clamp d5. You play …Nf6 and …O-O."],
      ["Open", "Nc3 Bg7 Be3 Nf6", "Normal Dragon shapes, but …d5 comes faster."],
    ],
    "Hit …d5 in one go if they skip c4.",
    "Against the Maroczy bind, be patient. …a6 and …b5 later.",
  ),
  e(
    "classical-sicilian",
    "Classical Sicilian",
    "B56",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6",
    [
      ["Richter", "Bg5 e6 Qd2", "They pin. You castle and play …a6."],
      ["Sozin", "Bc4 e6", "Bishop eyes f7. Blunt it with …e6 and …Be7."],
    ],
    "Develop naturally, then …a6 and a break with …d5 or …b5.",
    "Don't let the Bg5 pin sit forever. …Be7 or …h6 on time.",
  ),
  e(
    "scheveningen",
    "Scheveningen",
    "B80",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
    [
      ["Keres", "g4 Be7", "They storm. Castle and hit back in the center."],
      ["Classical", "Be2 Be7 O-O a6", "Small center. …b5 and …Qc7 next."],
    ],
    "Keep the small center (d6/e6), then …b5 and a knight to c4.",
    "Don't play …e5 unless you must. The hedgehog is the point.",
  ),
  e(
    "sveshnikov",
    "Sveshnikov Sicilian",
    "B33",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5",
    [
      ["Main", "Ndb5 d6", "They eye d6. You hold it and play …Be7."],
      ["Early a4", "Ndb5 d6 Nd6+", "If they hop in, trade and use the dark squares."],
    ],
    "Give the d5 hole, then use …f5 and the bishops.",
    "Don't lose the d6 pawn. Pieces first, then the f-break.",
  ),
  e(
    "taimanov",
    "Taimanov Sicilian",
    "B45",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6",
    [
      ["Main", "Nc3 Qc7", "Queen to c7. Then …a6 and …Nf6."],
      ["Flexible", "Nc3 a6", "Stop Nb5. Develop at your pace."],
    ],
    "…Qc7, …a6, and a later …b5. The c-file is yours.",
    "Don't castle into an English Attack unless you have …b5 ready.",
  ),
  e(
    "kan",
    "Kan Sicilian",
    "B41",
    "semi-open",
    "semi",
    "black",
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6",
    [
      ["Main", "Nc3 Qc7", "Same idea as Taimanov. Flexible pawns."],
      ["Bind", "c4 Nf6", "They grab space. You stay compact and wait."],
    ],
    "Keep the pawns flexible. …b5 or …d5 when the moment is clean.",
    "Don't commit …e5 early. The Kan likes options.",
  ),
  e(
    "alapin",
    "Alapin Sicilian",
    "B22",
    "semi-open",
    "semi",
    "white",
    "e4 c5 c3",
    [
      ["Center", "Nf6 e5 Nd5", "Kick the knight, then d4.",],
      ["Open d", "d5 exd5 Qxd5", "They take the center. You develop and castle."],
    ],
    "Play d4 and recapture with a pawn. A full classical center.",
    "If …d5 comes, develop and don't cling to the e-pawn.",
    "alapin",
  ),
  e(
    "smith-morra",
    "Smith–Morra Gambit",
    "B21",
    "semi-open",
    "semi",
    "white",
    "e4 c5 d4 cxd4 c3",
    [
      ["Accepted", "dxc3 Nxc3 Nc6", "Open files. Castle and pile on d6."],
      ["Declined", "Nf6 e5 Nd5", "They skip the pawn. You still grab space."],
    ],
    "Give a pawn for speed. Rooks on c and d, then e5.",
    "Don't take on d6 too soon. Development first.",
    "smith-morra",
  ),
  e(
    "grand-prix",
    "Grand Prix Attack",
    "B23",
    "semi-open",
    "system",
    "white",
    "e4 c5 Nc3 Nc6 f4",
    [
      ["Bishop", "g6 Nf3 Bg7 Bc4", "Bc4 and f5. Storm the king."],
      ["Closed", "d6 Nf3 g6", "Same pieces every game. Then Qe1-h4."],
    ],
    "f5, Qe1-h4, and a bishop on c4. Their king is the target.",
    "If they castle long, switch to the queenside. Don't force f5.",
    "grand-prix",
  ),
  e(
    "closed-sicilian",
    "Closed Sicilian",
    "B23",
    "semi-open",
    "system",
    "white",
    "e4 c5 Nc3 Nc6 g3",
    [
      ["Fianchetto", "g6 Bg2 Bg7 d3", "Slow build. Then f4 and Be3."],
      ["Early f4", "g6 f4 Bg7 Nf3", "Same Grand Prix idea with a bishop on g2."],
    ],
    "f4-f5 and a kingside lift. The g2 bishop holds the house.",
    "Don't open the center until your pieces are on their squares.",
  ),
  e(
    "rossolimo",
    "Rossolimo",
    "B30",
    "semi-open",
    "semi",
    "white",
    "e4 c5 Nf3 Nc6 Bb5",
    [
      ["Take", "g6 Bxc6", "Ruin their pawns. Then d3 and c3."],
      ["Keep", "g6 O-O Bg7", "Castle first. Trade on c6 when it helps."],
    ],
    "Double their c-pawns, then play against the dark squares.",
    "You don't need d4. A small center and a good bishop is enough.",
  ),
  e(
    "moscow-sicilian",
    "Moscow Variation",
    "B51",
    "semi-open",
    "semi",
    "white",
    "e4 c5 Nf3 d6 Bb5+",
    [
      ["Check", "Bd7 Bxd7+ Qxd7", "Trade, then c4 or d4."],
      ["Knight", "Nd7 d4", "They block. Open the middle anyway."],
    ],
    "Check, trade, and clamp with c4. No Open Sicilian theory.",
    "Castle and play against d6. Their dark squares can go weak.",
  ),
  e(
    "french",
    "French Defense",
    "C00",
    "semi-open",
    "semi",
    "black",
    "e4 e6",
    [
      ["Advance", "d4 d5 e5", "They close the center. You hit …c5 and …Nc6."],
      ["Exchange", "d4 d5 exd5", "Open and equal. Develop and castle."],
    ],
    "Chip the chain with …c5. The light-square bishop is the long job.",
    "Don't leave the bad bishop on c8 forever. …b6 or …Bd7-e8-g6.",
  ),
  e(
    "french-winawer",
    "French Winawer",
    "C15",
    "semi-open",
    "semi",
    "black",
    "e4 e6 d4 d5 Nc3 Bb4",
    [
      ["Advance", "e5 c5", "Pin and hit the chain. Queenside play."],
      ["Exchange", "exd5 exd5", "They dodge. Play a normal IQP or even game."],
    ],
    "Give the bishop for a wrecked white queenside, then storm …c5.",
    "King safety first. The Winawer can get wild on both wings.",
  ),
  e(
    "french-classical",
    "French Classical",
    "C11",
    "semi-open",
    "semi",
    "black",
    "e4 e6 d4 d5 Nc3 Nf6",
    [
      ["Steinitz", "e5 Nfd7", "They close. You hit …c5 and …f6."],
      ["Burn", "Bg5 dxe4", "They pin. You can take and develop."],
    ],
    "…c5 and …f6 vs the e5 wedge. That's the French story.",
    "The c8 bishop waits. Don't trade your good dark-square bishop cheap.",
  ),
  e(
    "french-tarrasch",
    "French Tarrasch",
    "C03",
    "semi-open",
    "semi",
    "white",
    "e4 e6 d4 d5 Nd2",
    [
      ["Closed", "Nf6 e5 Nfd7", "You keep the pawn chain. Then c3 and Bd3."],
      ["Open", "c5 exd5 exd5", "IQP or hanging pawns. Piece play."],
    ],
    "Avoid the Winawer pin. Build e5 and attack the king.",
    "If they play …c5, develop and don't cling to d4 at all costs.",
  ),
  e(
    "french-advance",
    "French Advance",
    "C02",
    "semi-open",
    "semi",
    "white",
    "e4 e6 d4 d5 e5",
    [
      ["Main", "c5 c3 Nc6 Nf3", "Hold d4. Then Bd3 and castle."],
      ["Milner", "c5 c3 Qb6 Nf3", "They hit d4 twice. You over-protect."],
    ],
    "Over-protect d4, then swing pieces toward the black king.",
    "Don't let …cxd4 wreck the chain unless you recapture with a pawn.",
  ),
  e(
    "french-exchange",
    "French Exchange",
    "C01",
    "semi-open",
    "semi",
    ["white", "black"],
    "e4 e6 d4 d5 exd5 exd5",
    [
      ["Symmetry", "Nf3 Nf6 Bd3", "Develop, castle, play for a tiny edge."],
      ["IQP path", "c4", "Open c. Isolated pawn, open pieces."],
    ],
    "If you want a fight, play c4 and use the open files.",
    "Don't shuffle. Castle and put rooks on e and c.",
  ),
  e(
    "french-kia",
    "French King's Indian Attack",
    "C00",
    "semi-open",
    "system",
    "white",
    "e4 e6 d3 d5 Nd2 Nf6 Ngf3",
    [
      ["Setup", "c5 g3 Nc6 Bg2", "Same pieces every game. Then O-O and e5."],
      ["Storm", "Be7 e5 Nfd7 g3", "Lock the center, then h-pawn and kingside."],
    ],
    "Lock e5, then throw the h-pawn and a knight to h4.",
    "Don't play d4. This is a system — same squares, every time.",
    "french-kia",
  ),
  e(
    "caro-kann",
    "Caro-Kann",
    "B10",
    "semi-open",
    "semi",
    "black",
    "e4 c6",
    [
      ["Classical", "d4 d5 Nc3 dxe4", "Trade, then …Bf5 and a safe king."],
      ["Advance", "d4 d5 e5 Bf5", "Bishop out first. Then …e6 and …c5."],
    ],
    "Get the light-square bishop out, then chip …c5.",
    "Solid first. The Caro wins endings, not 12-move mates.",
    "caro-kann",
  ),
  e(
    "caro-classical",
    "Caro-Kann Classical",
    "B18",
    "semi-open",
    "semi",
    "black",
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5",
    [
      ["Main", "Ng3 Bg6 h4 h6", "Bishop stays. Then …e6 and …Nf6."],
      ["Quiet", "Ng3 Bg6 Nf3 Nd7", "Develop. Castle short and play …c5."],
    ],
    "Tuck the bishop, castle, then …c5 in the center.",
    "Don't let h4-h5 trap the bishop. Always have …h6 ready.",
  ),
  e(
    "caro-advance",
    "Caro-Kann Advance",
    "B12",
    "semi-open",
    "semi",
    ["white", "black"],
    "e4 c6 d4 d5 e5",
    [
      ["Short", "Bf5 Nf3 e6", "Bishop out. Then …c5."],
      ["Tal", "Bf5 h4", "They storm. You stay calm and hit …c5."],
    ],
    "White wants a kingside bind. Black chips the base with …c5.",
    "Don't close the bishop in. …Bf5 before …e6 is the rule.",
    "caro-kann",
  ),
  e(
    "caro-fantasy",
    "Caro-Kann Fantasy",
    "B12",
    "semi-open",
    "semi",
    "white",
    "e4 c6 d4 d5 f3",
    [
      ["Take", "dxe4 fxe4 e5 Nf3", "Open f. Then Bc4 and castle."],
      ["Hold", "e6 Nc3", "They keep the tension. You still develop."],
    ],
    "Open the f-file and point a bishop at f7.",
    "If they don't take, just develop and treat it like a Vienna.",
    "caro-fantasy",
  ),
  e(
    "caro-panov",
    "Caro-Kann Panov",
    "B13",
    "semi-open",
    "semi",
    "white",
    "e4 c6 d4 d5 exd5 cxd5 c4",
    [
      ["IQP", "Nf6 Nc3 e6 Nf3", "Isolated d-pawn. Pieces, not pawns."],
      ["Take", "Nf6 Nc3 Nc6", "They pressure d4. You castle and use the files."],
    ],
    "Accept an IQP. Attack before the ending.",
    "Rooks on c and e. The d4 pawn is a space-giver, not a weakness yet.",
  ),
  e(
    "caro-two-knights",
    "Caro-Kann Two Knights",
    "B10",
    "semi-open",
    "semi",
    "white",
    "e4 c6 Nc3 d5 Nf3",
    [
      ["Main", "Bg4 h3 Bxf3", "They pin. You take space and castle."],
      ["Take", "dxe4 Nxe4", "Open. Develop and play d4 next."],
    ],
    "Skip the long Classical tree. Fast development and d4.",
    "If they pin, don't wreck the kingside pawns for nothing.",
  ),
  e(
    "pirc",
    "Pirc Defense",
    "B07",
    "semi-open",
    "system",
    "black",
    "e4 d6 d4 Nf6 Nc3 g6",
    [
      ["Classical", "Nf3 Bg7 Be2 O-O", "Castle, then …e5 or …c5."],
      ["Austrian", "f4 Bg7 Nf3 O-O", "They storm. You hit …c5 in the center."],
    ],
    "Let them take the center, then strike …e5 or …c5.",
    "Don't castle into a ready f4-f5 unless …c5 is already coming.",
    "pirc",
  ),
  e(
    "modern",
    "Modern Defense",
    "B06",
    "semi-open",
    "system",
    "black",
    "e4 g6",
    [
      ["Main", "d4 Bg7 Nc3 d6", "Same as a Pirc, knight still on g8."],
      ["Averbakh", "d4 Bg7 c4 d6", "They take a lot of space. You wait, then …e5."],
    ],
    "Fianchetto first. Hit the big center when it overextends.",
    "Don't grab pawns on d4 too early. Finish development.",
  ),
  e(
    "alekhine",
    "Alekhine Defense",
    "B02",
    "semi-open",
    "semi",
    "black",
    "e4 Nf6",
    [
      ["Four Pawns", "e5 Nd5 d4 d6 c4 Nb6 f4", "They take the lot. You chip it."],
      ["Modern", "e5 Nd5 d4 d6 Nf3", "Quieter. …Bg4 and pressure d4."],
    ],
    "Lure the pawns forward, then chop the overextended center.",
    "The knight on b6 needs a job. …Bg4 and …e6 keep you alive.",
    "alekhine",
  ),
  e(
    "scandinavian",
    "Scandinavian",
    "B01",
    "semi-open",
    "semi",
    "black",
    "e4 d5",
    [
      ["Qa5", "exd5 Qxd5 Nc3 Qa5", "Queen steps aside. Then …Nf6 and …c6."],
      ["Modern", "exd5 Nf6 d4 Nxd5", "Knight recaptures. Safer queen."],
    ],
    "Bring the queen home, then …Bf5 / …Bg4 and castle.",
    "Don't leave the queen on d5. One check and she is lost.",
    "scandinavian",
  ),
  e(
    "nimzowitsch-def",
    "Nimzowitsch Defense",
    "B00",
    "semi-open",
    "semi",
    "black",
    "e4 Nc6",
    [
      ["Center", "d4 d5", "Hit the middle at once."],
      ["Colorado", "Nf3 f5", "Wild. Only if you want a fight on move two."],
    ],
    "Pressure e4 and d4 with pieces, not a pawn wall.",
    "If they play d4, choose …d5 or …e5 and stick to it.",
  ),
  e(
    "owens",
    "Owen's Defense",
    "B00",
    "semi-open",
    "semi",
    "black",
    "e4 b6",
    [
      ["Fianchetto", "d4 Bb7", "Bite e4. Then …e6 and …Nf6."],
      ["Center", "d4 Bb7 Bd3 e6", "They guard e4. You still castle and play …c5."],
    ],
    "The b7 bishop stares at e4. Chip with …c5.",
    "Don't get squeezed. …e6 and …Nf6 before you hunt pawns.",
  ),
  e(
    "qgd",
    "Queen's Gambit Declined",
    "D30",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 e6",
    [
      ["Orthodox", "Nc3 Nf6 Bg5 Be7", "Develop, castle, then …c5 or …dxc4."],
      ["Exchange", "Nc3 Nf6 cxd5 exd5", "Minority attack vs their hanging …c6."],
    ],
    "Free the c8 bishop, then break …c5.",
    "Don't take on c4 too early unless you can hold the pawn.",
  ),
  e(
    "qgd-exchange",
    "QGD Exchange",
    "D35",
    "closed",
    "semi",
    "white",
    "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5",
    [
      ["Minority", "Bg5 Be7 e3 c6", "b4-b5. Ruin their queenside pawns."],
      ["Nge2", "Bg5 c6 e3 Bf5 Nge2", "Stop …Bf5 ideas, then castle."],
    ],
    "Minority attack: a- and b-pawns to wreck c6.",
    "Don't rush e4 unless the pieces are ready. The ending is your friend.",
    "queens-gambit",
  ),
  e(
    "qga",
    "Queen's Gambit Accepted",
    "D20",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 dxc4",
    [
      ["Main", "Nf3 Nf6 e3 e6", "They take the pawn back. You castle and …c5."],
      ["Early e4", "e4 e5", "They grab the center. Hit it at once."],
    ],
    "Give the pawn, finish development, then …c5 and …e5.",
    "Don't cling to c4. Development beats a doomed extra pawn.",
  ),
  e(
    "slav",
    "Slav Defense",
    "D10",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 c6",
    [
      ["Main", "Nf3 Nf6 Nc3 dxc4", "Take, then …Bf5 and …e6."],
      ["Exchange", "cxd5 cxd5", "Open c. Symmetric, but you can still play."],
    ],
    "Get the bishop out to f5 before …e6.",
    "The Slav is a wall. Don't invent a pawn storm on move eight.",
    "slav",
  ),
  e(
    "semi-slav",
    "Semi-Slav",
    "D43",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6",
    [
      ["Meran", "e3 Nbd7 Bd3 dxc4", "…b5 and a queenside expansion."],
      ["Botvinnik", "Bg5 dxc4", "Sharp. Only if you know the pawn grab."],
    ],
    "Take on c4, then …b5 and …Bb7. The c-file opens.",
    "The light-square bishop is the problem. Free it or play …e5.",
  ),
  e(
    "tarrasch-def",
    "Tarrasch Defense",
    "D32",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 e6 Nc3 c5",
    [
      ["IQP", "cxd5 exd5 Nf3 Nc6", "Isolated d-pawn. Pieces go to active squares."],
      ["Take", "cxd5 cxd4", "They can recapture. Keep developing."],
    ],
    "Accept the IQP. Activity on every file.",
    "Don't trade into a dead ending with the isolated pawn.",
  ),
  e(
    "chigorin",
    "Chigorin Defense",
    "D07",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 Nc6",
    [
      ["Main", "Nf3 Bg4", "Pin and pressure d4."],
      ["Early Nc3", "Nc3 dxc4", "Take and develop. Pieces, not pawns."],
    ],
    "Use knights and pins. Don't build a pawn wall.",
    "If they take on d5, recapture with a piece when you can.",
  ),
  e(
    "london",
    "London System",
    "D02",
    "closed",
    "system",
    "white",
    "d4 d5 Nf3 Nf6 Bf4",
    [
      ["Setup", "e6 e3 Bd6", "Same pieces: e3, c3, Bd3, Nbd2."],
      ["Job", "c5 e3 Nc6 c3", "They hit the center. You hold and castle."],
    ],
    "Bishop on f4, then Ne5 and a kingside lift.",
    "Don't play c4 too early. The system is the solid triangle.",
    "london",
  ),
  e(
    "jobava-london",
    "Jobava London",
    "D00",
    "closed",
    "system",
    "white",
    "d4 d5 Nc3 Nf6 Bf4",
    [
      ["Nb5", "c6 Nb5", "Hop in. Eye c7 and the dark squares."],
      ["Storm", "e6 Nb5 Na6 e3", "If they kick, keep developing and play e4 later."],
    ],
    "Nb5, Qd2, and a kingside pawn storm if they castle short.",
    "This is not a quiet London. Castle when the hunt is ready.",
    "jobava-london",
  ),
  e(
    "colle",
    "Colle System",
    "D04",
    "closed",
    "system",
    "white",
    "d4 d5 Nf3 Nf6 e3",
    [
      ["Setup", "e6 Bd3 c5", "Bd3, Nbd2, then e4."],
      ["Zukertort", "e6 Bd3 c5 b3", "Fianchetto the queen bishop too."],
    ],
    "The e4 break is the whole opening. Time it after Bd3.",
    "Don't play c4. This system wants a small center and one break.",
  ),
  e(
    "torre",
    "Torre Attack",
    "A46",
    "closed",
    "system",
    "white",
    "d4 Nf6 Nf3 e6 Bg5",
    [
      ["Pin", "c5 e3", "Hold the pin. Then Nbd2 and c3."],
      ["Take", "h6 Bxf6 Qxf6", "They ask. You ruin the kingside a little."],
    ],
    "Keep the pin, castle, and play e4 or Ne5.",
    "A system: same pieces vs many Black setups.",
  ),
  e(
    "trompowsky",
    "Trompowsky",
    "A45",
    "closed",
    "semi",
    "white",
    "d4 Nf6 Bg5",
    [
      ["Take", "Ne4 Bf4", "They hop. You keep the bishop and play e3."],
      ["Pin", "e6 e4 h6", "They kick. Decide whether to take on f6."],
    ],
    "Ruin their kingside pawns or hop the knight around d2-c4.",
    "Don't play it as a pure London. The early Bg5 is the point.",
  ),
  e(
    "veresov",
    "Veresov Attack",
    "D01",
    "closed",
    "semi",
    "white",
    "d4 Nf6 Nc3 d5 Bg5",
    [
      ["Pin", "Nbd7 Nf3", "Develop. Then e3 or e4."],
      ["Jobava cousin", "e6 f3", "Build e4. Same Jobava energy."],
    ],
    "Pin, then e4. Attack before they castle.",
    "If they play …c5, open the middle and use the c-file.",
  ),
  e(
    "blackmar-diemer",
    "Blackmar–Diemer",
    "D00",
    "closed",
    "semi",
    "white",
    "d4 d5 e4",
    [
      ["Accepted", "dxe4 Nc3 Nf6 f3", "Give a pawn. Open f and castle long."],
      ["Declined", "e6 e5", "They skip it. You take space and develop."],
    ],
    "Open the f-file and throw pieces at the king.",
    "Only if you like gambits. Else play a London.",
  ),
  e(
    "catalan",
    "Catalan",
    "E00",
    "closed",
    "system",
    "white",
    "d4 Nf6 c4 e6 g3",
    [
      ["Open", "d5 Bg2 dxc4", "They take. You castle and hunt c4."],
      ["Closed", "d5 Bg2 Be7", "They hold. You still castle and play Qc2."],
    ],
    "The g2 bishop rakes the queenside. Pressure c4 and b7.",
    "Don't rush e4. The long diagonal is the plan.",
  ),
  e(
    "nimzo",
    "Nimzo-Indian",
    "E20",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 e6 Nc3 Bb4",
    [
      ["Rubinstein", "e3 O-O", "They play solid. You castle and hit …c5 or …d5."],
      ["Classical", "Qc2 O-O", "They want the bishop pair. You take on c3 or keep it."],
    ],
    "Pin the knight, double their pawns, then attack the wreck.",
    "If you don't take on c3, keep the pin until it hurts them.",
  ),
  e(
    "queens-indian",
    "Queen's Indian",
    "E12",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 e6 Nf3 b6",
    [
      ["Fianchetto", "g3 Bb7 Bg2", "Both bishops on the long lines."],
      ["Petrosian", "a3 Bb7", "They stop …Bb4. You still castle and play …c5."],
    ],
    "The b7 bishop bites the center. Break with …c5.",
    "Don't lock the bishop in with …d5 too soon.",
  ),
  e(
    "kings-indian",
    "King's Indian",
    "E60",
    "indian",
    "system",
    "black",
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6",
    [
      ["Classical", "Nf3 O-O Be2 e5", "Lock the center, then …f5.",],
      ["Samisch", "f3 O-O Be3 e5", "They build a wall. You still …f5 later."],
    ],
    "Close the center, then storm the king with …f5-f4.",
    "Don't open the queenside unless you must. Your play is the kingside.",
    "kings-indian",
  ),
  e(
    "kid-samisch",
    "King's Indian Sämisch",
    "E80",
    "indian",
    "semi",
    ["white", "black"],
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3",
    [
      ["Main", "O-O Be3 e5", "White wants Qd2 and h4. Black prepares …f5."],
      ["Benoni shape", "O-O Be3 c5", "They change the structure. Play the c-file."],
    ],
    "White: Qd2, O-O-O, and the h-pawn. Black: …f5 and a piece sac on the dark squares.",
    "Whoever opens the wrong file first usually loses.",
    "kings-indian",
  ),
  e(
    "kid-mdp",
    "KID Mar del Plata",
    "E97",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7",
    [
      ["Storm", "Ne1 Nd7", "Knight swings. Then …f5 and …f4."],
      ["Bayonet", "b4 Nh5", "They expand queenside. You still storm the king."],
    ],
    "…f5-f4, …g5, and a rook lift. Race their queenside.",
    "Don't stop to grab a queenside pawn. The king hunt is the point.",
    "kings-indian",
  ),
  e(
    "grunfeld",
    "Grünfeld",
    "D80",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 g6 Nc3 d5",
    [
      ["Exchange", "cxd5 Nxd5 e4 Nxc3 bxc3", "They take the center. You chip …c5."],
      ["Russian", "Nf3 Bg7 Qb3", "They pressure d5. You develop and castle."],
    ],
    "Let them build a big center, then hit it with …c5 and …Nc6.",
    "The g7 bishop is the hero. Don't trade it for a knight.",
  ),
  e(
    "grunfeld-ex",
    "Grünfeld Exchange",
    "D85",
    "indian",
    "semi",
    ["white", "black"],
    "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3",
    [
      ["Main", "Bg7 Be3 c5", "…c5 and …Qa5. Pressure the hanging center."],
      ["Modern", "Bg7 Nf3 c5 Rb1", "They guard b2. You still hit d4."],
    ],
    "Black chips the center. White uses the extra space to attack.",
    "Don't let the c- and d-pawns sit forever. One of them must move.",
  ),
  e(
    "bogo",
    "Bogo-Indian",
    "E11",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 e6 Nf3 Bb4+",
    [
      ["Check", "Bd2 Qe7", "Keep the pin idea. Then …O-O and …d6."],
      ["Knight", "Nbd2 O-O", "They block. You castle and play …d5 or …c5."],
    ],
    "Check, castle, then …c5 or …d5. Simple and solid.",
    "Don't take on d2 unless it wrecks their pieces.",
  ),
  e(
    "modern-benoni",
    "Modern Benoni",
    "A60",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 c5 d5 e6 Nc3 exd5 cxd5 d6",
    [
      ["Fianchetto", "Nf3 g6", "…Bg7, …O-O, then …b5."],
      ["Classical", "e4 g6 Nf3 Bg7", "They take the center. You use the queenside majority."],
    ],
    "The queenside pawns roll. …b5 and the c-file.",
    "Don't get crushed in the center. …Re8 and …a6 before the storm.",
    "modern-benoni",
  ),
  e(
    "czech-benoni",
    "Czech Benoni",
    "A56",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 c5 d5 e5",
    [
      ["Closed", "Nc3 d6 e4 Be7", "Locked center. Then …O-O and …Ne8-g5."],
      ["Kingside", "Nc3 d6 e4 Nbd7", "Prepare …f5. Slow, but it bites."],
    ],
    "Lock the center, then …f5 on the king.",
    "This is cramped. Don't open it until the pieces have squares.",
  ),
  e(
    "benko",
    "Benko Gambit",
    "A57",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 c5 d5 b5",
    [
      ["Accepted", "cxb5 a6", "Give a pawn. Open a and b for the rooks."],
      ["Declined", "Nf3 Bb7", "They keep the pawn. You still pressure the long diagonal."],
    ],
    "Open the a- and b-files. The rooks do the work.",
    "Don't rush to win the pawn back. Pressure is the payment.",
    "benko",
  ),
  e(
    "budapest",
    "Budapest Gambit",
    "A51",
    "indian",
    "semi",
    "black",
    "d4 Nf6 c4 e5",
    [
      ["Adler", "dxe5 Ng4 Nf3", "They guard. You hit e5 and develop."],
      ["Kieninger", "dxe5 Ng4 Bf4 Nc6 Nf3 Bb4+", "Pin and take on e5 with a piece."],
    ],
    "Give a pawn for development and a pin on the queenside.",
    "If they cling to e5, pile pieces on it. Don't grab too soon.",
    "budapest",
  ),
  e(
    "old-indian",
    "Old Indian",
    "A53",
    "indian",
    "system",
    "black",
    "d4 Nf6 c4 d6",
    [
      ["Main", "Nc3 e5", "Hold e5. Then …Be7 and …O-O."],
      ["Knight", "Nc3 Nbd7 e4 e5", "Same as a Lion vs d4."],
    ],
    "A solid wall. Then …e5 and a later …f5.",
    "Don't fianchetto unless you mean to play a King's Indian.",
  ),
  e(
    "dutch-leningrad",
    "Dutch Leningrad",
    "A87",
    "indian",
    "semi",
    "black",
    "d4 f5 c4 Nf6 Nc3 g6",
    [
      ["Setup", "Nf3 Bg7 g3 O-O", "Fianchetto, then …d6 and …Qe8."],
      ["Storm", "g3 Bg7 Bg2 O-O Nf3 d6", "…Qe8-h5 and a kingside lift."],
    ],
    "…Qe8-h5 and the f-pawn already gained space.",
    "Watch e6. A hole there loses games. …d6 and …Nc6 help.",
    "dutch-leningrad",
  ),
  e(
    "dutch-stonewall",
    "Dutch Stonewall",
    "A90",
    "indian",
    "system",
    "black",
    "d4 f5 c4 e6 Nf3 Nf6 g3 d5",
    [
      ["Wall", "Bg2 c6 O-O Bd6", "Pawns on f5-e6-d5-c6. Knight to e4."],
      ["Early Ne5", "Bg2 c6 O-O Bd6 Nc3 O-O", "Same wall. Then …Qe8."],
    ],
    "Park a knight on e4 and swing the queen to h5.",
    "The c8 bishop is bad. …b6 or a later …e5 if they let you.",
  ),
  e(
    "dutch-classical",
    "Dutch Classical",
    "A96",
    "indian",
    "semi",
    "black",
    "d4 f5 c4 e6 Nf3 Nf6 g3 Be7",
    [
      ["Main", "Bg2 O-O O-O d6", "Flexible. Then …Qe8 and …e5."],
      ["Ilyin", "Bg2 O-O O-O Ne4", "Hop to e4 early. Same attack idea."],
    ],
    "Castle, then …Qe8 and …e5. The f-pawn supports the break.",
    "Don't stonewall unless you mean it. Keep …d6 as an option.",
  ),
  e(
    "english",
    "English Opening",
    "A10",
    "flank",
    "system",
    "white",
    "c4",
    [
      ["Reversed Sicilian", "e5 Nc3 Nf6", "You are Black's Sicilian, one tempo up."],
      ["Indian", "Nf6 Nc3 g6", "They fianchetto. You can play g3 too."],
    ],
    "Control d5. Then expand with b4 or break in the center.",
    "Don't rush d4 unless the pieces are ready. The c-pawn is the hero.",
    "english",
  ),
  e(
    "english-sym",
    "English Symmetrical",
    "A30",
    "flank",
    "semi",
    ["white", "black"],
    "c4 c5",
    [
      ["Four knights", "Nc3 Nc6 Nf3 Nf6", "Maneuver. Then d4 or b4."],
      ["Hedgehog", "Nf3 Nf6 g3 b6", "They stay small. You probe and wait."],
    ],
    "The first one to break with d4 (or …d5) sets the story.",
    "Don't invent a kingside storm. This is a squeeze.",
  ),
  e(
    "english-botvinnik",
    "English Botvinnik",
    "A26",
    "flank",
    "system",
    "white",
    "c4 e5 Nc3 Nc6 g3 g6 Bg2 Bg7 e4",
    [
      ["Clamp", "d6 Nge2", "You own d5. Then d3 and O-O."],
      ["Break", "d6 d3 f5", "They hit f5. You hold the hole on d5."],
    ],
    "The Botvinnik bind: pawns on c4 and e4. Sit on d5.",
    "Don't play d4 and give the hole away.",
    "english",
  ),
  e(
    "reti",
    "Réti Opening",
    "A04",
    "flank",
    "system",
    "white",
    "Nf3 d5 c4",
    [
      ["Main", "c6 g3 Nf6", "Fianchetto and pressure d5."],
      ["Take", "d4 b4", "They push. You expand on the queenside."],
    ],
    "Chip the center from the side. The g2 bishop does the work.",
    "You can still transpose to a Catalan. That's fine.",
  ),
  e(
    "kia",
    "King's Indian Attack",
    "A07",
    "flank",
    "system",
    "white",
    "Nf3 d5 g3",
    [
      ["Setup", "Nf6 Bg2 e6 O-O", "Nbd2, d3, e4. Same every game."],
      ["Vs French", "c5 Bg2 Nc6 d3", "Then e4 and a kingside storm."],
    ],
    "Lock e5, then the h-pawn and a knight to h4.",
    "System chess. Don't mix in a random d4.",
    "french-kia",
  ),
  e(
    "birds",
    "Bird's Opening",
    "A02",
    "flank",
    "system",
    "white",
    "f4",
    [
      ["From", "e5 fxe5 d6", "They gambit. You can take or skip."],
    ["Dutch reversed", "d5 Nf3 Nf6", "Stonewall or Leningrad, you are White."],
    ],
    "A Dutch with an extra tempo. Use the f-file.",
    "Watch e1–h4. A queen check can ruin the king.",
  ),
  e(
    "larsen",
    "Larsen's Opening",
    "A01",
    "flank",
    "system",
    "white",
    "b3",
    [
      ["Fianchetto", "e5 Bb2 Nc6", "Bite e5. Then e3 and Nf3."],
      ["Indian", "Nf6 Bb2 g6", "They fianchetto too. Play a slow squeeze."],
    ],
    "The b2 bishop is the opening. Point it at e5 and g7.",
    "Don't open the center until that bishop has a target.",
  ),
  e(
    "polish",
    "Polish Opening",
    "A00",
    "flank",
    "semi",
    "white",
    "b4",
    [
      ["Main", "e5 Bb2 Bxb4 Bxe5", "Trade a wing pawn for the center pawn."],
      ["Indian", "Nf6 Bb2 g6", "They stay flexible. You expand with a3 and e3."],
    ],
    "Grab space on the queenside and keep the long diagonal.",
    "Don't overextend. One extra pawn move can leave holes.",
  ),
  e(
    "grob",
    "Grob",
    "A00",
    "irregular",
    "semi",
    "white",
    "g4",
    [
      ["Spike", "d5 Bg2", "Bishop on the long line. Then c4."],
      ["Early h", "d5 h3", "Guard g4. Then Bg2."],
    ],
    "Shock value, then the g2 bishop. Don't hunt a mate on move six.",
    "If they take g4, develop and use the open g-file.",
  ),
  e(
    "black-lion",
    "Black Lion",
    "C41",
    "semi-open",
    "system",
    "black",
    "e4 d6 d4 Nf6 Nc3 Nbd7",
    [
      ["Coil", "Nf3 e5 Bc4 Be7", "…c6, …Qc7, …h6, then the lion spring."],
      ["Philidor", "Nf3 e5 Be2 Be7", "Same wall. Castle and wait for …Nh5."],
    ],
    "Coil, then …Nh5 and …f5. The kingside opens for you.",
    "Don't rush the spring. The setup is the whole opening.",
    "black-lion",
  ),
  e(
    "hippo",
    "Hippopotamus",
    "B00",
    "irregular",
    "system",
    "black",
    "e4 g6 d4 Bg7 Nc3 d6",
    [
      ["Setup", "Be3 a6 Qd2 b6", "Both bishops fianchetto. Then …e6 and …Ne7."],
      ["Break", "Nf3 Nd7 Be2 e6", "Wait, then …e5 or …c5."],
    ],
    "Look like you are doing nothing. Then break the center in one go.",
    "Don't break too soon. The Hippo waits for them to overextend.",
  ),
  e(
    "st-george",
    "St. George",
    "B00",
    "irregular",
    "semi",
    "black",
    "e4 a6",
    [
      ["Main", "d4 b5", "Expand on the queenside. Then …Bb7."],
      ["Center", "d4 e6", "Transposes toward a French with …a6.",],
    ],
    "…b5 and …Bb7. Bite e4 from the side.",
    "Don't forget the king. Castle before the wing gets too wide.",
  ),
  e(
    "borg",
    "Borg Defense",
    "B00",
    "irregular",
    "semi",
    "black",
    "e4 g5",
    [
      ["Take", "d4 h6", "Guard g5. Then …Bg7."],
      ["Center", "d4 Bg7", "They can take g5. You develop anyway."],
    ],
    "A joke that can bite if they grab too much.",
    "Treat it as a Modern with a loose g-pawn. Castle and hit the center.",
  ),
  e(
    "nimzo-rubinstein",
    "Nimzo Rubinstein",
    "E40",
    "indian",
    "semi",
    ["white", "black"],
    "d4 Nf6 c4 e6 Nc3 Bb4 e3",
    [
      ["Main", "O-O Bd3 d5", "Solid. Then Nf3 and O-O."],
      ["Hübner", "c5 Bd3 Nc6", "They chip c5. You stay on the light squares."],
    ],
    "White wants e4 later. Black doubles the c-pawns or hits …c5.",
    "Don't rush the center break. The pin decides when it is time.",
  ),
  e(
    "caro-bronstein",
    "Caro-Kann Bronstein–Larsen",
    "B16",
    "semi-open",
    "semi",
    "black",
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6 Nxf6+ gxf6",
    [
      ["Open g", "Nf3 Bf5", "Use the g-file. Castle long."],
      ["Quiet", "c3 Bf5", "They stay solid. You still develop and castle."],
    ],
    "Accept the wrecked pawns. The g-file and bishop pair are the pay.",
    "King to the queenside. Don't castle into your own open g-file.",
  ),
  e(
    "slav-exchange",
    "Slav Exchange",
    "D10",
    "closed",
    "semi",
    ["white", "black"],
    "d4 d5 c4 c6 cxd5 cxd5",
    [
      ["Symmetry", "Nc3 Nf6 Nf3 Nc6", "Develop. The c-file is the fight."],
      ["Early Bf4", "Nc3 Nf6 Bf4", "London ideas in a Slav shell."],
    ],
    "Fight for c5 / …c4. The open c-file is the whole game.",
    "Don't make it a draw on purpose. One minority idea still exists.",
  ),
  e(
    "semi-slav-meran",
    "Semi-Slav Meran",
    "D47",
    "closed",
    "semi",
    "black",
    "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5",
    [
      ["Main", "Bd3 a6", "…c5 next. The queenside expands."],
      ["Anti", "Be2 Bb7", "They stay safe. You still play …c5."],
    ],
    "…b5, …a6, …c5. That's the Meran machine.",
    "Free the c8 bishop or the opening has no point.",
  ),
  e(
    "open-sicilian",
    "Open Sicilian",
    "B32",
    "semi-open",
    "semi",
    "white",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4",
    [
      ["Main", "Nf6 Nc3", "Every Open Sicilian starts here. Then pick a setup."],
      ["Prins", "Nf6 f3", "Stop …d5. Then Be3 and Qd2."],
    ],
    "Take the center, castle (often long), and storm the king.",
    "Don't mix systems. Pick Yugoslav, English Attack, or Classical.",
  ),
  e(
    "yugoslav",
    "Yugoslav Attack",
    "B76",
    "semi-open",
    "semi",
    "white",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2",
    [
      ["Long castle", "Nc6 O-O-O", "Opposite castling. h4-h5 and Bh6."],
      ["Short", "Nc6 Bc4", "They can still castle short. Same pieces, slower hunt."],
    ],
    "Bh6, h4-h5, and open the h-file. Race their c-file.",
    "Don't wander. Every move should help the king hunt.",
    "dragon",
  ),
  e(
    "english-attack",
    "Najdorf English Attack",
    "B90",
    "semi-open",
    "semi",
    "white",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3",
    [
      ["Storm", "Be7 Qd2 O-O O-O-O", "Opposite castling. g4 and h4."],
      ["Short", "Be7 Qd2 O-O Be2", "Safer king. Still g4 later."],
    ],
    "Castle long, then g4-h4. The Najdorf king is the target.",
    "Watch …b5 and …Nc4. Their queenside is just as fast.",
  ),
  e(
    "london-kid",
    "London vs King's Indian",
    "A48",
    "closed",
    "system",
    "white",
    "d4 Nf6 Nf3 g6 Bf4",
    [
      ["Setup", "Bg7 e3 d6", "Same London pieces. Then h3 and c3."],
      ["Ne5", "Bg7 e3 O-O Be2", "Castle and hop Ne5."],
    ],
    "The London still works. Ne5 and a kingside lift.",
    "Don't let …c5 and …Qb6 bully d4. Over-protect.",
    "london",
  ),
  e(
    "reti-kid",
    "Réti vs King's Indian",
    "A05",
    "flank",
    "system",
    "white",
    "Nf3 Nf6 g3 g6",
    [
      ["Double fianchetto", "Bg2 Bg7 O-O O-O", "Then c4 or d3. Slow squeeze."],
      ["c4", "c4 Bg7 Bg2 O-O", "English-Réti hybrid. Sit on d5."],
    ],
    "Control d5 from the flank. Don't rush a pawn storm.",
    "You can still transpose to a Catalan or KIA.",
  ),
];
