import type { Opening } from "./types";

/**
 * Black Lion — user is Black.
 * Lion setup: …d6, …Nf6, …Nbd7, …e5, …Be7, …c6, then 0-0 / …Qc7 / …h6 / …Re8 / …Nf8-g6.
 * 30 full moves vs the common Bc4 + 0-0 Italian-Philidor shell.
 */
export const blackLion: Opening = {
  id: "black-lion",
  name: "Black Lion",
  shortName: "Lion",
  side: "black",
  versus: "1.e4 Bc4 shell",
  blurb: "Philidor teeth. Hide the king, coil …e5, then the Lion yawns.",
  story: {
    cast: "You are a lion that looks like a house cat.",
    conflict: "White wants a cheap Italian attack on f7.",
    plan: "Coil, castle, …Nf8-g6, then …e4 or a queenside yawn.",
  },
  moves: [
    "e4",
    "d6",
    "d4",
    "Nf6",
    "Nc3",
    "Nbd7",
    "Nf3",
    "e5",
    "Bc4",
    "Be7",
    "O-O",
    "c6",
    "a4",
    "O-O",
    "Re1",
    "Qc7",
    "h3",
    "h6",
    "Be3",
    "Re8",
    "Nh4",
    "Nf8",
    "Nf5",
    "Bxf5",
    "exf5",
    "e4",
    "d5",
    "c5",
    "Bf4",
    "Qd7",
    "Qd2",
    "a6",
    "a5",
    "Rac8",
    "Ra3",
    "Bd8",
    "Rb3",
    "Bc7",
    "Ne2",
    "Qe7",
    "Ng3",
    "N8d7",
    "Be2",
    "Ne5",
    "Rec1",
    "c4",
    "Rb4",
    "Nd3",
    "cxd3",
    "cxd3",
    "Qe3",
    "d2",
    "Bf1",
    "d1=Q",
    "Rxd1",
    "Qe5",
    "Qd2",
    "Qxf5",
    "Be2",
    "Nd7",
  ],
  chunks: [
    { fromPly: 0, toPly: 7, name: "Lion e5 break", job: "…d6 …Nf6 …Nbd7 …e5" },
    { fromPly: 8, toPly: 13, name: "Hide then castle", job: "…Be7 …c6. Then 0-0." },
    { fromPly: 14, toPly: 19, name: "Coil the queen", job: "…Qc7 …h6 …Re8" },
    { fromPly: 20, toPly: 25, name: "Kill the jumper", job: "…Nf8. Take Nf5. Push …e4." },
    { fromPly: 26, toPly: 31, name: "Close the center", job: "…c5. Queen tucks. …a6." },
    { fromPly: 32, toPly: 37, name: "Lion yawn", job: "Rooks. Bishop slides to c7." },
    { fromPly: 38, toPly: 43, name: "Reload the hops", job: "Queen to e7. …N8d7-e5." },
    { fromPly: 44, toPly: 49, name: "d3 wedge", job: "…c4 …Nd3. Pass the pawn." },
    { fromPly: 50, toPly: 55, name: "Queen the pawn", job: "…d2. Then d1=Q." },
    { fromPly: 56, toPly: 59, name: "Loot f5", job: "…Qxf5. You cashed in." },
  ],
  pins: [
    { afterPly: 7, label: "at the e5 pin…" },
    { afterPly: 13, label: "at the castle lock…" },
    { afterPly: 21, label: "at the Nf8 coil…" },
    { afterPly: 25, label: "at the e4 wedge…" },
    { afterPly: 37, label: "at the c7 battery…" },
    { afterPly: 43, label: "at the e5 outpost…" },
    { afterPly: 47, label: "at the d3 fork…" },
    { afterPly: 51, label: "at the passed pawn…" },
    { afterPly: 53, label: "at the promotion…" },
    { afterPly: 57, label: "at the f5 loot…" },
  ],
  storyBeats: [
    { afterPly: 7, beat: "Cast: the Lion is in the center." },
    { afterPly: 13, beat: "King hidden. They have no cheap mate." },
    { afterPly: 25, beat: "Conflict: you shove …e4 in their face." },
    { afterPly: 51, beat: "Plan: the d-pawn. That's the bite." },
  ],
  coach: [
    { afterPly: -1, text: "Lion sleeps. Then bites." },
    { afterPly: 1, text: "…d6. Same house. Different teeth." },
    { afterPly: 3, text: "…Nf6. Poke e4." },
    { afterPly: 5, text: "…Nbd7. Not a Pirc. Not yet." },
    { afterPly: 7, text: "…e5. The Lion is awake." },
    { afterPly: 9, text: "…Be7. Cover f7. No drama." },
    { afterPly: 11, text: "…c6. The Lion's spine." },
    { afterPly: 13, text: "Castle. They wanted f7. Missed." },
    { afterPly: 15, text: "Queen to c7. Coil." },
    { afterPly: 17, text: "…h6. No Bg5. Air for the king." },
    { afterPly: 19, text: "Rook to e8. You want …e4." },
    { afterPly: 21, text: "…Nf8. This hop is the Lion." },
    { afterPly: 23, text: "Take it. That knight was the only idea." },
    { afterPly: 25, text: "…e4. Shove. That's the bite." },
    { afterPly: 27, text: "…c5. Close it. You like this." },
    { afterPly: 29, text: "Queen tucks. Nothing hanging." },
    { afterPly: 31, text: "…a6. Room. Then the yawn." },
    { afterPly: 33, text: "Rook to c8. The file will matter." },
    { afterPly: 35, text: "Bishop slides. c7 is the battery." },
    { afterPly: 37, text: "There. The Lion's yawn." },
    { afterPly: 39, text: "Queen to e7. Reload the e-file." },
    { afterPly: 41, text: "Knight back to d7. Same hop." },
    { afterPly: 43, text: "…Ne5. Outpost. Sit." },
    { afterPly: 45, text: "…c4. Wedge. Knight wants d3." },
    { afterPly: 47, text: "…Nd3. That's the fork they feared." },
    { afterPly: 49, text: "Pass it. One pawn. Whole plan." },
    { afterPly: 51, text: "d2. They have to babysit." },
    { afterPly: 53, text: "Queen it. That's the bite." },
    { afterPly: 55, text: "…Qe5. Centralize. Take f5." },
    { afterPly: 57, text: "Loot. You earned that pawn." },
    { afterPly: 59, text: "Book's done. Extra pawn. Convert." },
  ],
  plans: {
    steady:
      "Babiesit d2 / the e-file. Trade queens if they offer. Knights belong on e5.",
    creative:
      "If the d-pawn dies, play for …b5 and a rook on the c-file. Dark squares stay yours.",
    aggressive:
      "If they let d2 live, queen it. Then loot f5 and play for the king — extra queen, extra pawn.",
  },
  depthNote:
    "30 moves vs the common Bc4 / 0-0 / a4 shell. Moves 1–16 are the Lion setup from the book; …Nf8, …Bxf5, …e4 and the …Nd3 idea are model attacking play. 150 Attack (Be3+Qd2+f3) and Austrian-style f4 are later adds.",
};
