export const fingerprints: Record<string, string[]> = {
  "scotch-gambit": ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Bc4"],
  "evans-gambit": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4"],
  "italian-attack": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "d4"],
  "vienna-gambit": ["e4", "e5", "Nc3", "Nf6", "f4"],
  "kings-gambit": ["e4", "e5", "f4"],
  "grand-prix": ["e4", "c5", "Nc3", "Nc6", "f4"],
  "smith-morra": ["e4", "c5", "d4", "cxd4", "c3"],
  "french-kia": ["e4", "e6", "d3"],
  "caro-fantasy": ["e4", "c6", "d4", "d5", "f3"],
  "london": ["d4", "d5", "Bf4"],
  "jobava-london": ["d4", "Nf6", "Nc3", "d5", "Bf4"],
  "pirc": ["e4", "d6", "d4", "Nf6", "Nc3", "g6"],
  "black-lion": ["e4", "d6", "d4", "Nf6", "Nc3", "Nbd7"],
  "dragon": ["e4", "c5", "Nf3", "d6", "d4"],
  "scandinavian": ["e4", "d5", "exd5", "Qxd5", "Nc3", "Qa5"],
  "alekhine": ["e4", "Nf6", "e5", "Nd5", "d4", "d6", "c4", "Nb6", "f4"],
  "kings-indian": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"],
  "modern-benoni": ["d4", "Nf6", "c4", "c5", "d5", "e6"],
  "benko": ["d4", "Nf6", "c4", "c5", "d5", "b5"],
  "dutch-leningrad": ["d4", "f5", "g3", "Nf6", "Bg2", "g6"],
  "budapest": ["d4", "Nf6", "c4", "e5"],
};

