import type { Opening } from "./types";

/**
 * London System — user is White.
 * Model line vs the most common amateur setup: ...d5 / ...e6 / ...c5 / ...Bd6.
 * 30 full moves. Ideas past move ~16 are typical middlegame, not forced engine book.
 */
export const london: Opening = {
  id: "london",
  name: "London System",
  shortName: "London",
  side: "white",
  versus: "…d5 / …e6 / …c5",
  blurb: "Triangle, keep the bishop, sit on e5. You squeeze. They suffocate.",
  story: {
    cast: "You are the wall with a poison bishop.",
    conflict: "Black hits c5 and wants your London bishop dead.",
    plan: "Castle, plant Ne5, then squeeze the kingside or clamp c5.",
  },
  moves: [
    "d4",
    "d5",
    "Bf4",
    "Nf6",
    "e3",
    "e6",
    "Nf3",
    "c5",
    "c3",
    "Nc6",
    "Nbd2",
    "Bd6",
    "Bg3",
    "O-O",
    "Bd3",
    "b6",
    "Ne5",
    "Bb7",
    "f4",
    "Ne7",
    "Qf3",
    "Nd7",
    "O-O",
    "f5",
    "Qe2",
    "Nf6",
    "Ndf3",
    "Ne4",
    "Bxe4",
    "dxe4",
    "Nd2",
    "Bd5",
    "c4",
    "Bb7",
    "Rad1",
    "Qc7",
    "Bh4",
    "Rad8",
    "Bxe7",
    "Qxe7",
    "Rfe1",
    "cxd4",
    "exd4",
    "Bxe5",
    "fxe5",
    "Rd7",
    "Nb3",
    "Rfd8",
    "Qe3",
    "h6",
    "Nc5",
    "Bc8",
    "b4",
    "a6",
    "a4",
    "Kh7",
    "Rf1",
    "Kg8",
    "Rd2",
    "Kh8",
  ],
  chunks: [
    { fromPly: 0, toPly: 5, name: "London triangle", job: "d4, Bf4, e3 — the wall" },
    { fromPly: 6, toPly: 11, name: "Knights vs c5", job: "Develop. Guard d4." },
    { fromPly: 12, toPly: 15, name: "Keep the bishop", job: "Bg3. Don't donate it." },
    { fromPly: 16, toPly: 21, name: "Ne5 outpost", job: "Plant the knight. Lift the queen." },
    { fromPly: 22, toPly: 27, name: "Castle then clamp", job: "King safe. Reload f3." },
    { fromPly: 28, toPly: 33, name: "Take the tension", job: "Bxe4, then chip c4." },
    { fromPly: 34, toPly: 39, name: "Pin and trade", job: "Rooks in. Bh4. Take e7." },
    { fromPly: 40, toPly: 45, name: "Open the wedge", job: "Recapture. e5 pawn lives." },
    { fromPly: 46, toPly: 51, name: "Knight to c5", job: "Nb3-c5. Best square." },
    { fromPly: 52, toPly: 59, name: "Queenside clamp", job: "b4, a4, lift the rooks." },
  ],
  pins: [
    { afterPly: 5, label: "at the triangle lock…" },
    { afterPly: 12, label: "at the bishop save…" },
    { afterPly: 16, label: "at the e5 pin…" },
    { afterPly: 22, label: "at the castle lock…" },
    { afterPly: 38, label: "at the e7 trade…" },
    { afterPly: 44, label: "at the e5 wedge…" },
    { afterPly: 50, label: "at the c5 outpost…" },
  ],
  storyBeats: [
    { afterPly: 5, beat: "Cast: quiet triangle. That's you." },
    { afterPly: 16, beat: "Conflict: the outpost is the fight." },
    { afterPly: 22, beat: "King tucked. Now squeeze." },
    { afterPly: 44, beat: "Plan: the wedge. Don't give it back." },
  ],
  coach: [
    { afterPly: -1, text: "Triangle first. Don't rush." },
    { afterPly: 0, text: "d4. You own the dark squares." },
    { afterPly: 2, text: "This bishop is the soul." },
    { afterPly: 4, text: "Triangle locked. Breathe." },
    { afterPly: 6, text: "Knight out. No heroics." },
    { afterPly: 8, text: "c3. d4 is a rock." },
    { afterPly: 10, text: "Both knights. Then the bishop lives." },
    { afterPly: 12, text: "He wanted it. You said no." },
    { afterPly: 14, text: "Aim the battery at h7." },
    { afterPly: 16, text: "Sit on e5. Don't hop off." },
    { afterPly: 18, text: "f4. Space. That's the squeeze." },
    { afterPly: 20, text: "Queen lifts. Kingside." },
    { afterPly: 22, text: "King tucked. Play chess." },
    { afterPly: 24, text: "Queen tucks. Keep the squeeze." },
    { afterPly: 26, text: "Reload f3. The outpost stays." },
    { afterPly: 28, text: "Take it. Tension dies on your terms." },
    { afterPly: 32, text: "c4. Chip the chain." },
    { afterPly: 34, text: "Rook to the file." },
    { afterPly: 36, text: "Pin. Make him sweat." },
    { afterPly: 38, text: "Trade. You keep the bind." },
    { afterPly: 40, text: "Rook to e. Hold the wedge." },
    { afterPly: 42, text: "Open it. You asked for this." },
    { afterPly: 44, text: "Wedge. That's the whole plan." },
    { afterPly: 46, text: "Knight wants c5." },
    { afterPly: 48, text: "Hold e5. Don't donate." },
    { afterPly: 50, text: "Best square on the board." },
    { afterPly: 52, text: "Queenside clamp. Fix the pawns." },
    { afterPly: 54, text: "a4. No …b5." },
    { afterPly: 56, text: "Rook to f. Probe the file." },
    { afterPly: 58, text: "Book's done. You survived." },
  ],
  plans: {
    steady:
      "Hold e5. Trade a pair of rooks if they beg. Improve the king. Don't chase ghosts.",
    creative:
      "If they sit, lift a rook to f3-h3. The bishop on g3/h4 still bites.",
    aggressive:
      "b5 or g4 when the pieces are ready — not before. One break. All in.",
  },
  depthNote:
    "30 moves. Moves 1–16 are core London theory vs …d5/…c5/…Bd6. After that this is a model squeeze (Ne5, f4, c5 outpost) — not a forced engine book. Sidelines (…Bf5, …Qb6, Jobava 2.Nc3) are later adds.",
};
