import type { Opening } from "./types";

/**
 * Pirc Defense — user is Black vs 1.e4.
 * Classical System (White Be2 / Nf3 / 0-0). 30 full moves.
 * Austrian Attack (f4) is the main later add.
 */
export const pirc: Opening = {
  id: "pirc",
  name: "Pirc Defense",
  shortName: "Pirc",
  side: "black",
  versus: "1.e4 Classical",
  blurb: "Give them the center. Fianchetto. Then strike …e5 and hop knights.",
  story: {
    cast: "You are the counterpuncher in a small house.",
    conflict: "White wants space, then a kingside smash.",
    plan: "…e5, trade or hold, then c5-hops and the long bishop.",
  },
  moves: [
    "e4",
    "d6",
    "d4",
    "Nf6",
    "Nc3",
    "g6",
    "Nf3",
    "Bg7",
    "Be2",
    "O-O",
    "O-O",
    "c6",
    "a4",
    "Nbd7",
    "Re1",
    "e5",
    "h3",
    "Re8",
    "Bf1",
    "exd4",
    "Nxd4",
    "Nc5",
    "Bf4",
    "a5",
    "Qd2",
    "Qb6",
    "Rad1",
    "Nfd7",
    "Be3",
    "Qc7",
    "f3",
    "Ne5",
    "b3",
    "Be6",
    "Nde2",
    "Rad8",
    "Nf4",
    "Bc8",
    "Qf2",
    "b6",
    "Nd3",
    "Nexd3",
    "Bxd3",
    "Nd7",
    "Be2",
    "Ne5",
    "Nb1",
    "Bf8",
    "Nd2",
    "Bg7",
    "Rf1",
    "Qe7",
    "c3",
    "f5",
    "exf5",
    "gxf5",
    "f4",
    "Ng6",
    "Bd4",
    "Bxd4",
  ],
  chunks: [
    { fromPly: 0, toPly: 7, name: "Pirc house", job: "…d6 …Nf6 …g6 …Bg7" },
    { fromPly: 8, toPly: 13, name: "Castle plus c6", job: "King in. …c6 blunts d5." },
    { fromPly: 14, toPly: 19, name: "Lion strike e5", job: "…e5. That's the break." },
    { fromPly: 20, toPly: 25, name: "Knight to c5", job: "Hop. Queen eyes b6." },
    { fromPly: 26, toPly: 31, name: "Reload the hops", job: "…Nfd7-e5. Dual outposts." },
    { fromPly: 32, toPly: 37, name: "Develop and wait", job: "…Be6. Don't rush …f5." },
    { fromPly: 38, toPly: 43, name: "Trade the jumper", job: "Take on d3. Recycle." },
    { fromPly: 44, toPly: 49, name: "Bishop parked", job: "…Bf8-g7. The house stays." },
    { fromPly: 50, toPly: 55, name: "f5 break", job: "Now. Open the g-file." },
    { fromPly: 56, toPly: 59, name: "Dark-square trade", job: "Meet Bd4. You asked for this." },
  ],
  pins: [
    { afterPly: 9, label: "at the castle lock…" },
    { afterPly: 15, label: "at the e5 pin…" },
    { afterPly: 19, label: "at the center trade…" },
    { afterPly: 21, label: "at the c5 hop…" },
    { afterPly: 31, label: "at the e5 outpost…" },
    { afterPly: 53, label: "at the f5 break…" },
    { afterPly: 59, label: "at the bishop trade…" },
  ],
  storyBeats: [
    { afterPly: 7, beat: "Cast: small house. Long bishop." },
    { afterPly: 15, beat: "Conflict: you take the center back." },
    { afterPly: 21, beat: "Knights hop. That's the script." },
    { afterPly: 53, beat: "Plan: f5. Now you attack." },
  ],
  coach: [
    { afterPly: -1, text: "Let them have the center." },
    { afterPly: 1, text: "…d6. The house starts here." },
    { afterPly: 3, text: "…Nf6. Poke e4. Stay flexible." },
    { afterPly: 5, text: "Fianchetto. This bishop is the soul." },
    { afterPly: 7, text: "House built. Don't rush …e5." },
    { afterPly: 9, text: "Castle. Then the break." },
    { afterPly: 11, text: "…c6. Blunt d5. Room for the queen." },
    { afterPly: 13, text: "…Nbd7. Both knights. Then …e5." },
    { afterPly: 15, text: "There it is. The Pirc strike." },
    { afterPly: 17, text: "Rook to e8. The file will open." },
    { afterPly: 19, text: "Take on d4. You asked for air." },
    { afterPly: 21, text: "…Nc5. Hop. Eye e4 and a4." },
    { afterPly: 23, text: "…a5. Freeze the queenside." },
    { afterPly: 25, text: "Queen to b6. Pressure. Not a raid." },
    { afterPly: 27, text: "Reload. The f-knight wants e5." },
    { afterPly: 29, text: "Queen back. You baited the bishop." },
    { afterPly: 31, text: "Outpost. Sit. Don't hop off." },
    { afterPly: 33, text: "Develop. The wait is the skill." },
    { afterPly: 35, text: "Rook to the d-file. Quiet." },
    { afterPly: 37, text: "Bishop tucks. Nothing hanging." },
    { afterPly: 39, text: "…b6. Cover c5. No cheap shots." },
    { afterPly: 41, text: "Take the jumper. Recycle." },
    { afterPly: 43, text: "Knight back. Same idea, new square." },
    { afterPly: 45, text: "e5 again. You own that hole." },
    { afterPly: 47, text: "Tuck the bishop. Prophylaxis." },
    { afterPly: 49, text: "House rebuilt. Now the break." },
    { afterPly: 51, text: "Queen to e7. Support …f5." },
    { afterPly: 53, text: "f5. This is the Pirc plan." },
    { afterPly: 55, text: "g-file. Your king is safer than it looks." },
    { afterPly: 57, text: "Knight to g6. Eye f4 and e5." },
    { afterPly: 59, text: "Trade. Dark squares are yours." },
  ],
  plans: {
    steady:
      "Hold e5. Keep the long bishop. If they sit, improve …Kh8 and a rook to g8.",
    creative:
      "…c5 later if the d-file dies. Knights want d3 or f3 holes.",
    aggressive:
      "Stack the g-file. …Kh8, …Rg8, and throw the f-pawn if the king is ready.",
  },
  depthNote:
    "30 moves of the Classical Pirc (Be2 / 0-0). Moves 1–16 are core book; the rest is a model hop-and-…f5 middlegame. Austrian Attack (4.f4), 150 Attack, and Exchange lines are later adds.",
};
